#!/usr/bin/expect

#exp_internal 1

spawn nc localhost 10003
set one $spawn_id
spawn nc localhost 10004
set two $spawn_id

send -i one "write client21/igmp.join 225.1.1.1\r"
expect -i one "200"
sleep 2
send -i two "write client22/igmp.join 225.1.1.1\r"
expect -i two "200"
sleep 2
send -i one "write client21/igmp.leave 225.1.1.1\r"
expect -i one "200"
sleep 2
send -i two "write client22/igmp.leave 225.1.1.1\r"
expect -i two "200"
sleep 2
close -i one
close -i two
